# 网络请求设置
request:
  timeout: 10 # 超时设置
  ssl: false # ssl 设置

# 要抓取的 issues 配置
issues:
  repo: panoshu/friends # 仓库持有者/仓库名
  label: active # 只能配置 1 个或留空，留空则所有 open 的 issue 都会被抓取。配置 1 个时，issue 只有在具有该标签时才被抓取
  groups: # 填写用来分组的 label 名称。留空则所有被抓取的 issue 输出至 data.json，否则按照输出与组名同名的 json 文件
  sort: updated-desc # 排序，按最近更新，取消此项则按创建时间排序
